# -*- coding: utf-8 -*-
"""Diabetes Risk Predictor

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UygxfiBUL2na39rT57ijBTV3iA34OG4c

EXPLORING THE DATASET
"""

!pip install scikit-learn pandas numpy matplotlib seaborn xgboost lightgbm catboost --quiet

# Install dependencies as needed:
import pandas as pd
from pathlib import Path

# Display all columns and extend dataframe width
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 140)

# Use GitHub URL to read the CSV file directly
url = "https://raw.githubusercontent.com/DerickT02/diabetes_prediction_model/main/Diabetes-Data/diabetes_health_indicators.csv"
df = pd.read_csv(url, header=0, index_col=False)

print("First 5 records:")
print(df.head(), "\n\n")
print("Last 5 records:")
print(df.tail(), "\n\n")
print("Dataset Info:")
print(df.info(), "\n")
print(df.describe())

# Class distribution check
print("\nClass Distribution:")
print(df['Diabetes_binary'].value_counts())
print(f"Imbalance ratio: {df['Diabetes_binary'].value_counts()[0] / df['Diabetes_binary'].value_counts()[1]:.2f}:1")

import matplotlib.pyplot as plt

df.hist(bins=30, figsize=(14, 14))
plt.show()

"""DATA PRE-PROCESSING"""

# Fill missing values using a multivariate imputer
from sklearn.impute import KNNImputer
import numpy as np

# Features/Columns with missing values are imputed using mean-value from n nearest-neighbors found in training/data set
KNN_imputer = KNNImputer(n_neighbors=6)
bmi_output = KNN_imputer.fit_transform(df[ ["BMI"] ])
df["BMI"] = bmi_output
education_output = KNN_imputer.fit_transform(df[ ["Education"] ])
df["Education"] = education_output
print(df.info())

# Class Imbalance Note
print("\nClass Distribution (before balancing):")
print(df['Diabetes_binary'].value_counts())
print(f"Imbalance ratio: {df['Diabetes_binary'].value_counts()[0] / df['Diabetes_binary'].value_counts()[1]:.2f}:1")
print("\nNote: SMOTE will be applied after feature scaling to balance classes.")

"""FEATURE ENGINEERING

## EXPERIMENTS AND RESULTS

This section details the experimental setup, parameters used, and presents the key findings and results from various machine learning models. Figures, tables, and charts are utilized to effectively illustrate the performance and comparisons.
"""

# Feature Identification - Assigning dependant/independant variables
df = df.astype("float64")  # Convert dataframe to float
feats_X = df.iloc[:, [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21]] # 21 features total if we dont include target
target_y = pd.DataFrame(df.iloc[:, 0])  # column at index 0 (Diabetes_binary) is target

# Feature Generation - Creating new insightful features from a blend of existing features
feats_X["BMI_Category"] = pd.cut(
    feats_X["BMI"],
    bins=[0, 18.5, 25, 30, 35, 100],
    labels=[0, 1, 2, 3, 4]  # underweight, normal, overweight, obese I, obese II+
).astype("float64")

feats_X["IsSenior"] = (feats_X["Age"] >= 9).astype(float) # >= 9 60+

feats_X["PoorAct&PoorDiet"] = (
    (feats_X["PhysActivity"] == 0) & ((feats_X["Fruits"] == 0) | (feats_X["Veggies"] == 0))
).astype(float)

# Feature Selection - Ensuring the features we use will be useful in predicting target
# Correlation Analysis & Feature Selection

# BMI_Category was removed because it was highly inter-correlated (>0.85) with BMI — makes sense since it was derived directly from BMI.
# No features were weak enough (<0.02) to drop. Even AnyHealthcare at 0.023 squeaked past the threshold.
# What was kept: 23 features total, including your two engineered features (IsSenior and PoorAct&PoorDiet) which both showed meaningful correlation (0.24 and 0.12 respectively).

import seaborn as sns
import numpy as np

analysis_df = feats_X.copy()
analysis_df["Diabetes_binary"] = target_y.values

corr_matrix = analysis_df.corr()

# Correlation of every feature with the target, sorted by strength
target_corr = corr_matrix["Diabetes_binary"].drop("Diabetes_binary").sort_values(key=abs, ascending=False)
print("Feature correlations with Diabetes_binary:\n")
print(target_corr.to_string(), "\n")

# Heatmap of the full correlation matrix
plt.figure(figsize=(18, 14))
sns.heatmap(corr_matrix, annot=True, fmt=".2f", cmap="coolwarm", center=0, linewidths=0.5)
plt.title("Feature Correlation Heatmap")
plt.tight_layout()
plt.show()

# Drop features with very weak correlation to the target (|r| < 0.02)
weak_features = target_corr[abs(target_corr) < 0.02].index.tolist()
if weak_features:
    print(f"Dropping weakly correlated features: {weak_features}")
    feats_X.drop(columns=weak_features, inplace=True)
else:
    print("No weakly correlated features to drop.")

# Drop one of any feature pair with inter-correlation > 0.85 to reduce multicollinearity
corr_feats = feats_X.corr().abs()
upper_tri = corr_feats.where(np.triu(np.ones(corr_feats.shape), k=1).astype(bool))
redundant = [col for col in upper_tri.columns if any(upper_tri[col] > 0.85)]
if redundant:
    print(f"Dropping redundant (highly inter-correlated) features: {redundant}")
    feats_X.drop(columns=redundant, inplace=True)
else:
    print("No redundant features to drop.")

print(f"\nFinal feature set ({feats_X.shape[1]} features): {list(feats_X.columns)}")

# Feature Transformation/Normalization - Ensuring features are distributed evenly across dataset, eliminating skewness
# Every feature now has mean ≈ 0 and std = 1
from sklearn.preprocessing import StandardScaler
from imblearn.over_sampling import SMOTE
import numpy as np

scaler = StandardScaler()

feats_X_unscaled = pd.DataFrame(
    scaler.fit_transform(feats_X),
    columns=feats_X.columns,
    index=feats_X.index
)

print("\nUnscaled feature stats:")
print(feats_X.describe().loc[["mean", "std"]])

feats_X_scaled = pd.DataFrame(
    scaler.fit_transform(feats_X),
    columns=feats_X.columns,
    index=feats_X.index
)

print("\nScaled feature stats (mean ≈ 0, std ≈ 1):")
print(feats_X_scaled.describe().loc[["mean", "std"]])

# Apply SMOTE after scaling
sm = SMOTE(random_state=42)
feats_X_resampled, target_y_resampled = sm.fit_resample(
    feats_X_scaled, target_y['Diabetes_binary'].astype(int)
)
print(f"\nBefore SMOTE: {dict(zip(*np.unique(target_y['Diabetes_binary'].astype(int), return_counts=True)))}")
print(f"After SMOTE : {dict(zip(*np.unique(target_y_resampled, return_counts=True)))}")

import matplotlib.pyplot as plt
import numpy as np

# True original counts from raw dataset
original_no_diabetes = 213703
original_diabetes = 35346

fig, axes = plt.subplots(1, 2, figsize=(12, 4))

# Before SMOTE - true original dataset
axes[0].bar(['No Diabetes', 'Diabetes'], [original_no_diabetes, original_diabetes], color=['steelblue', 'tomato'])
axes[0].set_title('Class Distribution - BEFORE SMOTE')
axes[0].set_ylabel('Count')
axes[0].text(0, original_no_diabetes + 1000, str(original_no_diabetes), ha='center', fontweight='bold')
axes[0].text(1, original_diabetes + 1000, str(original_diabetes), ha='center', fontweight='bold')

# After SMOTE - balanced
after_counts = np.unique(target_y_resampled, return_counts=True)[1]
axes[1].bar(['No Diabetes', 'Diabetes'], after_counts, color=['steelblue', 'tomato'])
axes[1].set_title('Class Distribution - AFTER SMOTE')
axes[1].set_ylabel('Count')
for i, v in enumerate(after_counts):
    axes[1].text(i, v + 1000, str(v), ha='center', fontweight='bold')

plt.tight_layout()
plt.show()

print(f"Before SMOTE: No Diabetes={original_no_diabetes}, Diabetes={original_diabetes}")
print(f"Imbalance ratio: {original_no_diabetes/original_diabetes:.1f}:1")
print(f"After SMOTE : {dict(zip(['No Diabetes', 'Diabetes'], after_counts))}")

# Train / Test Split
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    feats_X_resampled, target_y_resampled,
    test_size=0.2, random_state=42, stratify=target_y_resampled
)
print(f"Training set : {X_train.shape}")
print(f"Test set     : {X_test.shape}")

# Selecting ML algorithm and tuning hyperparameters

from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, ExtraTreesClassifier
from sklearn.neural_network import MLPClassifier

ml_algorithm = "LogisticRegress" # LogisticRegress, KNN, SVM, DeciTree, RandFrst, ExtraTree, GradBoost, MLP

if ml_algorithm == "LogisticRegress":
    algorithm = LogisticRegression(class_weight="balanced", max_iter=2000)
elif ml_algorithm == "KNN":
    algorithm = KNeighborsClassifier(n_neighbors=15, weights="distance")
elif ml_algorithm == "SVM":
    algorithm = SVC(class_weight="balanced", probability=True)
elif ml_algorithm == "DeciTree":
    algorithm = DecisionTreeClassifier(class_weight="balanced", random_state=42)
elif ml_algorithm == "RandFrst":
    algorithm = RandomForestClassifier(n_estimators=100, class_weight="balanced", random_state=42, n_jobs=-1)
elif ml_algorithm == "ExtraTree":
    algorithm = ExtraTreesClassifier(n_estimators=100, class_weight="balanced", random_state=42, n_jobs=-1)
elif ml_algorithm == "GradBoost":
    algorithm = GradientBoostingClassifier(n_estimators=100, random_state=42)
elif ml_algorithm == "MLP":
    algorithm = MLPClassifier(hidden_layer_sizes=(64, 32), max_iter=500, random_state=42)
else:
    raise ValueError("Unknown ml_algorithm")

print(f"Selected algorithm: {ml_algorithm}")
print(f"Model: {algorithm}")

"""### 1. Traditional Machine Learning Model Comparison

> Add blockquote



This section evaluates the performance of several traditional machine learning algorithms, including Logistic Regression, Decision Tree, Random Forest, Extra Trees, Gradient Boosting, and a Multi-Layer Perceptron (MLP). The models are trained on the preprocessed and resampled data, and their performance metrics (Accuracy, Precision, Recall, F1-Score, and ROC-AUC) are compared to identify the most suitable baseline model.
"""

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score
import pandas as pd
import matplotlib.pyplot as plt

# Compare ALL Models
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, ExtraTreesClassifier
from sklearn.neural_network import MLPClassifier

models = {
    "LogisticRegression" : LogisticRegression(class_weight="balanced", max_iter=2000, n_jobs=-1),
    "DecisionTree"       : DecisionTreeClassifier(class_weight="balanced", random_state=42),
    "RandomForest"       : RandomForestClassifier(n_estimators=100, class_weight="balanced", random_state=42, n_jobs=-1),
    "ExtraTrees"         : ExtraTreesClassifier(n_estimators=100, class_weight="balanced", random_state=42, n_jobs=-1),
    "GradientBoosting"   : GradientBoostingClassifier(n_estimators=100, random_state=42),
    "MLP"                : MLPClassifier(hidden_layer_sizes=(64, 32), max_iter=500, random_state=42),
}

results = []
for name, model in models.items():
    print(f"Training {name}...")
    model.fit(X_train, y_train)
    preds = model.predict(X_test)
    proba = model.predict_proba(X_test)[:, 1]
    results.append({
        "Model"     : name,
        "Accuracy"  : round(accuracy_score(y_test, preds), 4),
        "Precision" : round(precision_score(y_test, preds), 4),
        "Recall"    : round(recall_score(y_test, preds), 4),
        "F1"        : round(f1_score(y_test, preds), 4),
        "ROC-AUC"   : round(roc_auc_score(y_test, proba), 4),
    })

results_df = pd.DataFrame(results).sort_values("ROC-AUC", ascending=False)
print("\n Model Comparison Table ")
print(results_df.to_string(index=False))
print(f"\nBest model by ROC-AUC: {results_df.iloc[0]['Model']}")

# Bar chart
results_df.set_index("Model")[["Accuracy", "F1", "ROC-AUC"]].plot(
    kind="bar", figsize=(12, 5), colormap="Set2"
)
plt.title("Model Comparison")
plt.ylabel("Score")
plt.xticks(rotation=30, ha="right")
plt.ylim(0.5, 1.0)
plt.tight_layout()
plt.show()

"""### 2. Boosting Models Comparison

Here, we compare the performance of advanced boosting algorithms: XGBoost, LightGBM, and CatBoost. These models are known for their strong predictive power and are often considered state-of-the-art for tabular data. Their metrics are evaluated against each other and the best-performing traditional models.
"""

# XGBoost + LightGBM + CatBoost
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from catboost import CatBoostClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score
import pandas as pd

boost_models = {
    "CatBoost" : CatBoostClassifier(
        iterations=200,
        learning_rate=0.05,
        depth=5,
        random_seed=42,
        verbose=0
    ),
    "XGBoost" : XGBClassifier(
        n_estimators=200,
        max_depth=5,
        learning_rate=0.05,
        random_state=42,
        n_jobs=-1,
        eval_metric='auc',
        verbosity=0
    ),
    "LightGBM" : LGBMClassifier(
        n_estimators=200,
        max_depth=5,
        learning_rate=0.05,
        random_state=42,
        n_jobs=-1,
        verbose=-1
    ),
}

boost_results = []
for name, model in boost_models.items():
    print(f"Training {name}...")
    model.fit(X_train, y_train)
    preds = model.predict(X_test)
    proba = model.predict_proba(X_test)[:, 1]
    boost_results.append({
        "Model"     : name,
        "Accuracy"  : round(accuracy_score(y_test, preds), 4),
        "Precision" : round(precision_score(y_test, preds), 4),
        "Recall"    : round(recall_score(y_test, preds), 4),
        "F1"        : round(f1_score(y_test, preds), 4),
        "ROC-AUC"   : round(roc_auc_score(y_test, proba), 4),
    })

boost_df = pd.DataFrame(boost_results).sort_values("ROC-AUC", ascending=False)
print("\n Boosting Models Comparison ")
print(boost_df.to_string(index=False))
print(f"\nBest boosting model: {boost_df.iloc[0]['Model']}")

# Update results_df to include boosting models
results_df = pd.concat([results_df, boost_df], ignore_index=True).sort_values("ROC-AUC", ascending=False)

# Ensemble Voting Classifier
from sklearn.ensemble import VotingClassifier, GradientBoostingClassifier, RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score
import pandas as pd
import matplotlib.pyplot as plt

ensemble = VotingClassifier(
    estimators=[
        ('gb',  GradientBoostingClassifier(n_estimators=100, random_state=42)),
        ('rf',  RandomForestClassifier(n_estimators=100, class_weight='balanced', random_state=42)),
        ('lr',  LogisticRegression(class_weight='balanced', max_iter=2000)),
    ],
    voting='soft',
    n_jobs=-1
)

print("Training Ensemble model...")
ensemble.fit(X_train, y_train)
ens_preds = ensemble.predict(X_test)
ens_proba = ensemble.predict_proba(X_test)[:, 1]

print("\n Ensemble Model Results ")
print(f"Accuracy  : {accuracy_score(y_test, ens_preds):.4f}")
print(f"Precision : {precision_score(y_test, ens_preds):.4f}")
print(f"Recall    : {recall_score(y_test, ens_preds):.4f}")
print(f"F1        : {f1_score(y_test, ens_preds):.4f}")
print(f"ROC-AUC   : {roc_auc_score(y_test, ens_proba):.4f}")

# Add ensemble to results
ensemble_row = pd.DataFrame([{
    "Model"     : "Ensemble (GB+RF+LR)",
    "Accuracy"  : round(accuracy_score(y_test, ens_preds), 4),
    "Precision" : round(precision_score(y_test, ens_preds), 4),
    "Recall"    : round(recall_score(y_test, ens_preds), 4),
    "F1"        : round(f1_score(y_test, ens_preds), 4),
    "ROC-AUC"   : round(roc_auc_score(y_test, ens_proba), 4),
}])

# results_df = pd.concat([results_df, ensemble_row], ignore_index=True).sort_values("ROC-AUC", ascending=False)
print("\n Full Model Comparison ")
print(results_df.to_string(index=False))

# Bar chart of all models
results_df.set_index("Model")[["Accuracy", "F1", "ROC-AUC"]].plot(
    kind="bar", figsize=(14, 5), colormap="Set2"
)
plt.title("All Models Comparison")
plt.ylabel("Score")
plt.xticks(rotation=30, ha="right")
plt.ylim(0.5, 1.0)
plt.tight_layout()
plt.show()

"""### 3. Deep Learning Model Evaluation

This section introduces a multi-layer perceptron (MLP) deep learning model. The architecture, training process, and performance metrics (accuracy, loss, precision, recall over epochs) are presented, along with the final evaluation metrics on the test set. Early stopping and learning rate reduction techniques are applied during training.
"""

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score

def accuracy(y_true, y_pred):
  return accuracy_score(y_true, y_pred)

def precision(y_true, y_pred):
  return precision_score(y_true, y_pred, zero_division=0)

def recall(y_true, y_pred):
  return recall_score(y_true, y_pred, zero_division=0)

def f1(y_true, y_pred):
  return f1_score(y_true, y_pred, zero_division=0)

def specificity(y_true, y_pred):
  return recall_score(y_true, y_pred, pos_label=0, zero_division=0)

def roc_auc(y_true, y_score):
  return roc_auc_score(y_true, y_score)

# Training the model, training metrics
from sklearn.model_selection import cross_val_predict

X_train = feats_X_scaled.copy()
y_train = target_y["Diabetes_binary"].astype(int)

# Cross-validated predicted labels
cv_preds = cross_val_predict(algorithm, X_train, y_train, cv=3, method='predict')
print("Shape of Output/Predictions: ", cv_preds.shape, "\n")

print("Training Metrics: ", "\n----------------")
print("Accuracy    : ", round(accuracy(y_train, cv_preds), 4))
print("Precision   : ", round(precision(y_train, cv_preds), 4))
print("Recall      : ", round(recall(y_train, cv_preds), 4))
print("F1          : ", round(f1(y_train, cv_preds), 4))
print("Specificity : ", round(specificity(y_train, cv_preds), 4))

if hasattr(algorithm, "predict_proba"):
    cv_scores = cross_val_predict(algorithm, X_train, y_train, cv=3, method="predict_proba")[:, 1]
    print("ROC-AUC     : ", round(roc_auc(y_train, cv_scores), 4))
elif hasattr(algorithm, "decision_function"):
    cv_scores = cross_val_predict(algorithm, X_train, y_train, cv=3, method="decision_function")
    print("ROC-AUC     : ", round(roc_auc(y_train, cv_scores), 4))
else:
    print("ROC-AUC     : not available")

# Model Testing/Generalization, evaluating performance
from sklearn.model_selection import cross_val_predict
from sklearn.metrics import confusion_matrix, classification_report, roc_curve, accuracy_score, f1_score
import matplotlib.pyplot as plt
import seaborn as sns

X_train_cv = feats_X_resampled.copy()
y_train_cv = target_y_resampled

cv_preds = cross_val_predict(algorithm, X_train_cv, y_train_cv, cv=5, method="predict")

if hasattr(algorithm, "predict_proba"):
    cv_scores = cross_val_predict(algorithm, X_train_cv, y_train_cv, cv=5, method="predict_proba")[:, 1]
elif hasattr(algorithm, "decision_function"):
    cv_scores = cross_val_predict(algorithm, X_train_cv, y_train_cv, cv=5, method="decision_function")
else:
    cv_scores = None

# Confusion matrix
cm = confusion_matrix(y_train_cv, cv_preds)
print("Confusion Matrix:")
print("                 Pred No Diab   Pred Diab")
print(f"Actual No Diab   {cm[0,0]:<14} {cm[0,1]}")
print(f"Actual Diab      {cm[1,0]:<14} {cm[1,1]}\n")

tn, fp, fn, tp = cm.ravel()
print(f"TN: {tn}")
print(f"FP: {fp}  (said diabetic, wasn't)")
print(f"FN: {fn}  (missed actual diabetics)")
print(f"TP: {tp}\n")

print("Classification Report:")
print(classification_report(y_train_cv, cv_preds, target_names=["No Diabetes", "Diabetes"], digits=4))

# ROC curve
if cv_scores is not None:
    fpr, tpr, _ = roc_curve(y_train_cv, cv_scores)
    plt.figure(figsize=(7, 6))
    plt.plot(fpr, tpr, label=f"{ml_algorithm} (AUC = {roc_auc_score(y_train_cv, cv_scores):.4f})")
    plt.plot([0, 1], [0, 1], "k--", label="Random")
    plt.xlabel("False Positive Rate")
    plt.ylabel("True Positive Rate")
    plt.title("ROC Curve")
    plt.legend(loc="lower right")
    plt.grid(alpha=0.3)
    plt.show()

# Overfitting Analysis
print("\n Overfitting Check ")
algorithm.fit(X_train, y_train)
train_preds = algorithm.predict(X_train)
test_preds  = algorithm.predict(X_test)

print(f"Train Accuracy : {accuracy_score(y_train, train_preds):.4f}")
print(f"Test  Accuracy : {accuracy_score(y_test,  test_preds):.4f}")
print(f"Train F1       : {f1_score(y_train, train_preds):.4f}")
print(f"Test  F1       : {f1_score(y_test,  test_preds):.4f}")

gap = accuracy_score(y_train, train_preds) - accuracy_score(y_test, test_preds)
if gap > 0.05:
    print(f"\n Possible overfitting detected (gap = {gap:.4f})")
elif gap < -0.05:
    print(f"\n Possible underfitting detected (gap = {gap:.4f})")
else:
    print(f"\n Model generalizes well (gap = {gap:.4f})")

# Visual confusion matrix heatmap
cm_test = confusion_matrix(y_test, test_preds)
plt.figure(figsize=(5, 4))
sns.heatmap(cm_test, annot=True, fmt='d', cmap='Blues',
            xticklabels=['No Diabetes', 'Diabetes'],
            yticklabels=['No Diabetes', 'Diabetes'])
plt.title(f'Confusion Matrix — {ml_algorithm} (Test Set)')
plt.ylabel('Actual')
plt.xlabel('Predicted')
plt.tight_layout()
plt.show()

# Final Summary
print("\n" + "=" * 50)
print("   PROJECT DELTA — FINAL RESULTS SUMMARY")
print("=" * 50)
print(results_df.to_string(index=False))
print(f"\n Best model by ROC-AUC: {results_df.iloc[0]['Model']}")

# Deep Learning Model

import tensorflow as tf
from tensorflow import keras
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score
import matplotlib.pyplot as plt

model_dl = keras.Sequential([
    keras.Input(shape=(X_train.shape[1],)),

    # Block 1
    keras.layers.Dense(512, activation='relu'),
    keras.layers.BatchNormalization(),
    keras.layers.Dropout(0.5),

    # Block 2
    keras.layers.Dense(256, activation='relu'),
    keras.layers.BatchNormalization(),
    keras.layers.Dropout(0.4),

    # Block 3
    keras.layers.Dense(128, activation='relu'),
    keras.layers.BatchNormalization(),
    keras.layers.Dropout(0.3),

    # Block 4
    keras.layers.Dense(64, activation='relu'),
    keras.layers.BatchNormalization(),
    keras.layers.Dropout(0.2),

    # Block 5
    keras.layers.Dense(32, activation='relu'),
    keras.layers.Dropout(0.1),

    # Output
    keras.layers.Dense(1, activation='sigmoid')
])

model_dl.compile(
    optimizer=keras.optimizers.Adam(learning_rate=0.001),
    loss='binary_crossentropy',
    metrics=['accuracy', tf.keras.metrics.AUC(name='auc'),
             tf.keras.metrics.Precision(name='precision'),
             tf.keras.metrics.Recall(name='recall')]
)

model_dl.summary()

early_stop = keras.callbacks.EarlyStopping(
    monitor='val_auc',
    patience=7,
    restore_best_weights=True,
    mode='max',
    verbose=1
)

reduce_lr = keras.callbacks.ReduceLROnPlateau(
    monitor='val_loss',
    factor=0.3,
    patience=3,
    min_lr=0.000001,
    verbose=1
)

history = model_dl.fit(
    X_train, y_train,
    epochs=100,
    batch_size=32,
    validation_data=(X_test, y_test),
    callbacks=[early_stop, reduce_lr],
    verbose=1
)

# Plot
fig, axes = plt.subplots(2, 2, figsize=(14, 10))

axes[0,0].plot(history.history['accuracy'],     label='Train')
axes[0,0].plot(history.history['val_accuracy'], label='Val')
axes[0,0].set_title('Accuracy')
axes[0,0].legend()
axes[0,0].grid(alpha=0.3)

axes[0,1].plot(history.history['loss'],     label='Train')
axes[0,1].plot(history.history['val_loss'], label='Val')
axes[0,1].set_title('Loss')
axes[0,1].legend()
axes[0,1].grid(alpha=0.3)

axes[1,0].plot(history.history['precision'],     label='Train')
axes[1,0].plot(history.history['val_precision'], label='Val')
axes[1,0].set_title('Precision')
axes[1,0].legend()
axes[1,0].grid(alpha=0.3)

axes[1,1].plot(history.history['recall'],     label='Train')
axes[1,1].plot(history.history['val_recall'], label='Val')
axes[1,1].set_title('Recall')
axes[1,1].legend()
axes[1,1].grid(alpha=0.3)

plt.tight_layout()
plt.show()

dl_preds = (model_dl.predict(X_test) > 0.5).astype(int)
dl_proba  = model_dl.predict(X_test)

print("\n Deep Learning Results ")
print(f"Accuracy  : {accuracy_score(y_test, dl_preds):.4f}")
print(f"Precision : {precision_score(y_test, dl_preds):.4f}")
print(f"Recall    : {recall_score(y_test, dl_preds):.4f}")
print(f"F1        : {f1_score(y_test, dl_preds):.4f}")
print(f"ROC-AUC   : {roc_auc_score(y_test, dl_proba):.4f}")

"""### 4. Tuned XGBoost and Threshold Optimization

This part focuses on a fine-tuned XGBoost model, showcasing improved performance through hyperparameter optimization. Additionally, a detailed threshold optimization analysis is performed to identify the optimal classification threshold that balances precision and recall, crucial for diabetes prediction where false negatives can have significant implications. The plot illustrates how various metrics change across different probability thresholds.
"""

from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score

xgb_tuned = XGBClassifier(
    n_estimators=1000,
    max_depth=7,
    learning_rate=0.005,
    subsample=0.8,
    colsample_bytree=0.7,
    min_child_weight=5,
    gamma=0.2,
    reg_alpha=0.1,
    reg_lambda=2.0,
    scale_pos_weight=1,
    random_state=42,
    n_jobs=-1,
    eval_metric='auc',
    verbosity=0,
    early_stopping_rounds=50
)

xgb_tuned.fit(
    X_train, y_train,
    eval_set=[(X_test, y_test)],
    verbose=False
)

xgb_preds = xgb_tuned.predict(X_test)
xgb_proba = xgb_tuned.predict_proba(X_test)[:, 1]

print("── Tuned XGBoost V2 Results ─────────────────────────────────")
print(f"Accuracy  : {accuracy_score(y_test, xgb_preds):.4f}")
print(f"Precision : {precision_score(y_test, xgb_preds):.4f}")
print(f"Recall    : {recall_score(y_test, xgb_preds):.4f}")
print(f"F1        : {f1_score(y_test, xgb_preds):.4f}")
print(f"ROC-AUC   : {roc_auc_score(y_test, xgb_proba):.4f}")

"""### Overfitting and Underfitting Analysis

To ensure our models generalize well to unseen data, we are comparing their performance on the training set versus the testing set.
"""

# Evaluate Train vs Test performance for key models to check for overfitting/underfitting
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.metrics import accuracy_score, f1_score
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from xgboost import XGBClassifier

# Re-initialize and fit key models to ensure they are in memory and avoid NameErrors
eval_models = {
    'Logistic Regression': LogisticRegression(class_weight="balanced", max_iter=2000, n_jobs=-1),
    'Random Forest': RandomForestClassifier(n_estimators=100, class_weight="balanced", random_state=42, n_jobs=-1),
    'Gradient Boosting': GradientBoostingClassifier(n_estimators=100, random_state=42),
    'Tuned XGBoost': XGBClassifier(n_estimators=1000, max_depth=7, learning_rate=0.005, subsample=0.8, colsample_bytree=0.7, random_state=42, n_jobs=-1)
}

overfit_results = []

for name, model in eval_models.items():
    print(f"Evaluating {name}...")
    model.fit(X_train, y_train)

    # Predictions on Training Set
    train_preds = model.predict(X_train)
    train_acc = accuracy_score(y_train, train_preds)
    train_f1 = f1_score(y_train, train_preds)

    # Predictions on Testing Set
    test_preds = model.predict(X_test)
    test_acc = accuracy_score(y_test, test_preds)
    test_f1 = f1_score(y_test, test_preds)

    overfit_results.append({
        'Model': name,
        'Train Accuracy': round(train_acc, 4),
        'Test Accuracy': round(test_acc, 4),
        'Accuracy Gap': round(train_acc - test_acc, 4),
        'Train F1': round(train_f1, 4),
        'Test F1': round(test_f1, 4),
        'F1 Gap': round(train_f1 - test_f1, 4)
    })

overfit_df = pd.DataFrame(overfit_results)
print("\n--- Overfitting/Underfitting Analysis ---")
display(overfit_df)

# Visualization of Train vs Test F1 Score
overfit_df.set_index('Model')[['Train F1', 'Test F1']].plot(kind='bar', figsize=(10, 5), colormap='viridis')
plt.title('Train vs Test F1 Score (Checking for Overfitting)')
plt.ylabel('F1 Score')
plt.xticks(rotation=0)
plt.legend(loc='lower right')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

"""#### Analysis of Generalization

Based on the table and chart above, we can evaluate the models for overfitting and underfitting:

*   **Generalization**: Most models show an exceptionally small gap (typically < 0.01) between training and testing metrics. For example, Logistic Regression and Gradient Boosting have nearly identical train and test scores. This indicates that the models **generalize very well** to unseen data and are not memorizing the training set.
*   **Overfitting**: The **Random Forest** model shows a larger gap between training and testing performance (e.g., higher training accuracy/F1 compared to test). This is a classic sign of mild overfitting, which is common in unpruned tree ensembles.
*   **Underfitting**: We do not observe severe underfitting in the top-performing models, as the base metrics (Test Accuracy ~75%, Test F1 ~76%) are solid given the complexity of the dataset. However, simpler models like Decision Trees (evaluated earlier) showed lower overall scores, which could be considered relative underfitting compared to the boosting ensembles.
*   **Tuned XGBoost**: The hyperparameter tuning applied to the XGBoost model (including regularization parameters like `reg_alpha`, `reg_lambda`, and `max_depth` restrictions) successfully kept the accuracy gap narrow, proving the model is robust and not overfit.
"""

# Threshold Optimization for XG Boost
# Instead of using the default cutoff of 0.50, it tests many different probability thresholds and checks how the model’s metrics change.
import numpy as np
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score
import matplotlib.pyplot as plt

thresholds       = np.arange(0.1, 0.9, 0.05)
f1_scores        = []
precision_scores = []
recall_scores    = []
accuracy_scores  = []

for t in thresholds:
    preds = (xgb_proba > t).astype(int)
    f1_scores.append(f1_score(y_test, preds, zero_division=0))
    precision_scores.append(precision_score(y_test, preds, zero_division=0))
    recall_scores.append(recall_score(y_test, preds, zero_division=0))
    accuracy_scores.append(accuracy_score(y_test, preds))

# Find threshold where precision crosses 80%
for i, (t, p) in enumerate(zip(thresholds, precision_scores)):
    if p >= 0.80:
        best_precision_threshold = t
        break

print(f"Threshold where Precision hits 80%: {best_precision_threshold:.2f}")

# Plot
plt.figure(figsize=(12, 5))
plt.plot(thresholds, f1_scores,        label='F1',        color='green',     marker='o')
plt.plot(thresholds, precision_scores, label='Precision', color='steelblue', marker='s')
plt.plot(thresholds, recall_scores,    label='Recall',    color='tomato',    marker='^')
plt.plot(thresholds, accuracy_scores,  label='Accuracy',  color='purple',    marker='D')
plt.axhline(y=0.80, color='black', linestyle='--', label='80% target')
plt.axvline(best_precision_threshold, color='red', linestyle='--', label=f'Threshold = {best_precision_threshold:.2f}')
plt.title('XGBoost - All Metrics vs Threshold')
plt.xlabel('Threshold')
plt.ylabel('Score')
plt.legend()
plt.grid(alpha=0.3)
plt.tight_layout()
plt.show()

# Results at best precision threshold
best_preds_xgb = (xgb_proba > best_precision_threshold).astype(int)
print(f"\n── XGBoost at Threshold {best_precision_threshold:.2f} ──────────────────────────")
print(f"Accuracy  : {accuracy_score(y_test, best_preds_xgb):.4f}")
print(f"Precision : {precision_score(y_test, best_preds_xgb):.4f}")
print(f"Recall    : {recall_score(y_test, best_preds_xgb):.4f}")
print(f"F1        : {f1_score(y_test, best_preds_xgb):.4f}")
print(f"ROC-AUC   : {roc_auc_score(y_test, xgb_proba):.4f}")

"""### 5. Final Model Performance Summary

Finally, all evaluated models, including traditional ML, boosting, deep learning, and tuned XGBoost (with both default and optimized thresholds), are consolidated into a comprehensive comparison table and bar chart. This summary highlights the best-performing model based on key metrics such as ROC-AUC, Accuracy, Precision, Recall, and F1-Score, providing a clear overview of the project's findings.
"""

# Save Models + Final Summary
import joblib
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

# Save models
joblib.dump(algorithm, 'diabetes_model.pkl')
print(f"ML model ({ml_algorithm}) saved as diabetes_model.pkl")

joblib.dump(scaler, 'scaler.pkl')
print("Scaler saved as scaler.pkl")

model_dl.save('diabetes_dl_model.keras')
print("Deep Learning model saved as diabetes_dl_model.keras")

joblib.dump(xgb_tuned, 'xgboost_model.pkl')
print("Tuned XGBoost model saved as xgboost_model.pkl")

# Threshold Optimization for XGBoost
thresholds       = np.arange(0.1, 0.9, 0.05)
f1_scores        = []
precision_scores = []
recall_scores    = []
accuracy_scores  = []

for t in thresholds:
    preds = (xgb_proba > t).astype(int)
    f1_scores.append(f1_score(y_test, preds, zero_division=0))
    precision_scores.append(precision_score(y_test, preds, zero_division=0))
    recall_scores.append(recall_score(y_test, preds, zero_division=0))
    accuracy_scores.append(accuracy_score(y_test, preds))

# Best F1 threshold
best_threshold_xgb = thresholds[np.argmax(f1_scores)]
best_preds_xgb     = (xgb_proba > best_threshold_xgb).astype(int)

# Plot threshold analysis
plt.figure(figsize=(12, 5))
plt.plot(thresholds, f1_scores,        label='F1',        color='green',     marker='o')
plt.plot(thresholds, precision_scores, label='Precision', color='steelblue', marker='s')
plt.plot(thresholds, recall_scores,    label='Recall',    color='tomato',    marker='^')
plt.plot(thresholds, accuracy_scores,  label='Accuracy',  color='purple',    marker='D')
plt.axhline(y=0.80, color='black', linestyle='--', label='80% target')
plt.axvline(best_threshold_xgb, color='red', linestyle='--', label=f'Best threshold = {best_threshold_xgb:.2f}')
plt.title('XGBoost - All Metrics vs Threshold')
plt.xlabel('Threshold')
plt.ylabel('Score')
plt.legend()
plt.grid(alpha=0.3)
plt.tight_layout()
plt.show()

# Build Complete Results Table
dl_row = pd.DataFrame([{
    "Model"     : "Deep Learning",
    "Accuracy"  : round(accuracy_score(y_test, dl_preds), 4),
    "Precision" : round(precision_score(y_test, dl_preds), 4),
    "Recall"    : round(recall_score(y_test, dl_preds), 4),
    "F1"        : round(f1_score(y_test, dl_preds), 4),
    "ROC-AUC"   : round(roc_auc_score(y_test, dl_proba), 4),
}])

xgb_default_row = pd.DataFrame([{
    "Model"     : "Tuned XGBoost (0.50)",
    "Accuracy"  : round(accuracy_score(y_test, xgb_preds), 4),
    "Precision" : round(precision_score(y_test, xgb_preds), 4),
    "Recall"    : round(recall_score(y_test, xgb_preds), 4),
    "F1"        : round(f1_score(y_test, xgb_preds), 4),
    "ROC-AUC"   : round(roc_auc_score(y_test, xgb_proba), 4),
}])

xgb_tuned_row = pd.DataFrame([{
    "Model"     : f"Tuned XGBoost ({best_threshold_xgb:.2f})",
    "Accuracy"  : round(accuracy_score(y_test, best_preds_xgb), 4),
    "Precision" : round(precision_score(y_test, best_preds_xgb), 4),
    "Recall"    : round(recall_score(y_test, best_preds_xgb), 4),
    "F1"        : round(f1_score(y_test, best_preds_xgb), 4),
    "ROC-AUC"   : round(roc_auc_score(y_test, xgb_proba), 4),
}])

final_results = pd.concat(
    [results_df[["Model","Accuracy","Precision","Recall","F1","ROC-AUC"]],
     dl_row, xgb_default_row, xgb_tuned_row],
    ignore_index=True
).sort_values("ROC-AUC", ascending=False).reset_index(drop=True)

# Print Final Summary
print("\n" + "=" * 65)
print("           PROJECT DELTA - FINAL RESULTS SUMMARY")
print("=" * 65)
print(final_results.to_string(index=False))
print(f"\nBest Overall Model : {final_results.iloc[0]['Model']}")
print(f"Best ROC-AUC       : {final_results['ROC-AUC'].max():.4f}")
print(f"Best Accuracy      : {final_results.loc[final_results['Accuracy'].idxmax(), 'Model']} ({final_results['Accuracy'].max():.4f})")
print(f"Best Precision     : {final_results.loc[final_results['Precision'].idxmax(), 'Model']} ({final_results['Precision'].max():.4f})")
print(f"Best Recall        : {final_results.loc[final_results['Recall'].idxmax(), 'Model']} ({final_results['Recall'].max():.4f})")
print(f"Best F1            : {final_results.loc[final_results['F1'].idxmax(), 'Model']} ({final_results['F1'].max():.4f})")
print("=" * 65)

# Final Bar Chart
final_results.set_index("Model")[["Accuracy", "Precision", "Recall", "F1", "ROC-AUC"]].plot(
    kind="bar", figsize=(16, 6), colormap="Set2"
)
plt.title("Project Delta - All Models Final Comparison")
plt.ylabel("Score")
plt.xticks(rotation=30, ha="right")
plt.ylim(0.5, 1.0)
plt.axhline(y=0.80, color='red', linestyle='--', linewidth=1.5, label='80% target')
plt.legend(loc='lower right')
plt.tight_layout()
plt.show()

"""### 6. Quality Control and Pipeline Testing

"""

print("Running Quality Control Tests...")

# UNIT TESTING (Testing individual components)

# Test A: Required columns exist
required_cols = ["Diabetes_binary",
    "HighBP","HighChol","CholCheck","BMI","Smoker","Stroke","HeartDiseaseorAttack",
    "PhysActivity","Fruits","Veggies","HvyAlcoholConsump","AnyHealthcare","NoDocbcCost",
    "GenHlth","MentHlth","PhysHlth","DiffWalk","Sex","Age","Education","Income"]
missing = [c for c in required_cols if c not in df.columns]
assert not missing, f"Unit Test Failed: Missing required columns: {missing}"

# Test B: Target is binary
target_vals = set(pd.Series(df["Diabetes_binary"]).dropna().unique().tolist())
assert target_vals.issubset({0, 1}), f"Unit Test Failed: Diabetes_binary not in {{0,1}}. Found: {target_vals}"

# Test C: Ensure Data Preprocessing removed all missing values
assert df.isnull().sum().sum() == 0, "Unit Test Failed: Null values still exist in the dataset."

# Test D: Ensure Feature Engineering created the correct columns that survived feature selection
expected_engineered_cols = ['IsSenior', 'PoorAct&PoorDiet']
for col in expected_engineered_cols:
    assert col in feats_X_resampled.columns, f"Unit Test Failed: Engineered feature '{col}' is missing from the final training set."

# Test E: Ensure engineered features are binary
for col in ["IsSenior", "PoorAct&PoorDiet"]:
    vals = set(pd.Series(feats_X[col]).dropna().unique().tolist())
    assert vals.issubset({0.0, 1.0}), f"Unit Test Failed: {col} not binary. Found: {vals}"

print("Passed all unit tests.")

# INTEGRATION TESTING (Testing how components work together)
# Test F: Ensure SMOTE correctly integrated with our pipeline and balanced the classes perfectly
import pandas as pd
class_counts = pd.Series(target_y_resampled).value_counts()
assert class_counts.iloc[0] == class_counts.iloc[1], f"Integration Test Failed: SMOTE did not balance classes. Ratio is {class_counts.iloc[0]}:{class_counts.iloc[1]}"

# Test G: Ensure train/test split integrated correctly
# Allowing a tolerance of 1 row due to rounding in train_test_split
assert abs(len(X_test) - len(target_y_resampled) * 0.2) <= 1, "Integration Test Failed: Test set size does not match the 20% split."

# Test H: Check Data Scaling Integration
# Ensure that scaled features actually have a mean near 0 and standard deviation near 1
assert np.allclose(feats_X_scaled.mean(), 0, atol=1e-7), "Integration Test Failed: Scaler did not center means to 0."

print("Passed all intergration tests")

# ACCEPTANCE TESTING (Testing if the final product meets customer requirements)
# Requirement #1: The model must be capable of predicting diabetes risk effectively (Baseline for effectiveness is set at 0.80 ROC-AUC).
best_model_auc = final_results.iloc[0]['ROC-AUC']
assert best_model_auc >= 0.80, f"Acceptance Test Failed: Best model ROC-AUC ({best_model_auc}) is below the acceptable clinical threshold of 0.80."

# Requirement 2: High Recall (Baseline for "High" is 0.75) for positive class (Diabetes).
best_model_recall = final_results.iloc[0]['Recall']
assert best_model_recall >= 0.75, f"Acceptance Test Failed: Best model Recall ({best_model_recall}) is below the acceptable threshold of 0.75."

print("Passed all acceptance tests")

print("All Quality Control Tests Passed Successfully.")

"""### 7. Demo: Predicting Diabetes with Tuned XGBoost

In this section, we showcase the model's practical application by predicting the diabetes risk for 10 hypothetical patients. We use the saved `scaler.pkl` to ensure the data is normalized correctly and the `xgboost_model.pkl` to generate predictions.
"""

import pandas as pd
import numpy as np
import joblib

scaler = joblib.load('scaler.pkl')
xgb_model = joblib.load('xgboost_model.pkl')

class Patient:
    def __init__(self, name, data_dict):
        self.name = name
        self.data = pd.DataFrame([data_dict])
        self.probability = None
        self.prediction = None

    def preprocess_and_predict(self, scaler, model, threshold=0.40):
        self.data['IsSenior'] = (self.data['Age'] >= 9).astype(float)
        self.data['PoorAct&PoorDiet'] = (
            (self.data['PhysActivity'] == 0) & ((self.data['Fruits'] == 0) | (self.data['Veggies'] == 0))
        ).astype(float)

        feature_cols = [
            'HighBP', 'HighChol', 'CholCheck', 'BMI', 'Smoker', 'Stroke',
            'HeartDiseaseorAttack', 'PhysActivity', 'Fruits', 'Veggies',
            'HvyAlcoholConsump', 'AnyHealthcare', 'NoDocbcCost', 'GenHlth',
            'MentHlth', 'PhysHlth', 'DiffWalk', 'Sex', 'Age', 'Education',
            'Income', 'IsSenior', 'PoorAct&PoorDiet'
        ]
        input_data = self.data[feature_cols]

        # Scale and Predict
        scaled_data = scaler.transform(input_data)
        self.probability = model.predict_proba(scaled_data)[0, 1]
        self.prediction = 'Diabetes' if self.probability > threshold else 'No Diabetes'


# Patient 1: High risk - High BP, High Chol, Overweight, Older
patient_1_data = {'HighBP': 1, 'HighChol': 1, 'CholCheck': 1, 'BMI': 32, 'Smoker': 1, 'Stroke': 0, 'HeartDiseaseorAttack': 0, 'PhysActivity': 0, 'Fruits': 0, 'Veggies': 1, 'HvyAlcoholConsump': 0, 'AnyHealthcare': 1, 'NoDocbcCost': 0, 'GenHlth': 4, 'MentHlth': 10, 'PhysHlth': 15, 'DiffWalk': 1, 'Sex': 1, 'Age': 11, 'Education': 4, 'Income': 5}
patient_1 = Patient(name="Patient_1", data_dict=patient_1_data)

# Patient 2: Low risk - Healthy BMI, Active, Young, Good Income
patient_2_data = {'HighBP': 0, 'HighChol': 0, 'CholCheck': 1, 'BMI': 22, 'Smoker': 0, 'Stroke': 0, 'HeartDiseaseorAttack': 0, 'PhysActivity': 1, 'Fruits': 1, 'Veggies': 1, 'HvyAlcoholConsump': 0, 'AnyHealthcare': 1, 'NoDocbcCost': 0, 'GenHlth': 1, 'MentHlth': 0, 'PhysHlth': 0, 'DiffWalk': 0, 'Sex': 0, 'Age': 4, 'Education': 6, 'Income': 8}
patient_2 = Patient(name="Patient_2", data_dict=patient_2_data)

# Patient 3: Borderline - High BP, Average BMI, Some physical activity
patient_3_data = {'HighBP': 1, 'HighChol': 0, 'CholCheck': 1, 'BMI': 28, 'Smoker': 0, 'Stroke': 0, 'HeartDiseaseorAttack': 0, 'PhysActivity': 1, 'Fruits': 1, 'Veggies': 1, 'HvyAlcoholConsump': 0, 'AnyHealthcare': 1, 'NoDocbcCost': 0, 'GenHlth': 2, 'MentHlth': 2, 'PhysHlth': 0, 'DiffWalk': 0, 'Sex': 1, 'Age': 8, 'Education': 6, 'Income': 7}
patient_3 = Patient(name="Patient_3", data_dict=patient_3_data)

# Patient 4: Very Low Risk - Young, Healthy, Active
patient_4_data = {'HighBP': 0, 'HighChol': 0, 'CholCheck': 1, 'BMI': 24, 'Smoker': 0, 'Stroke': 0, 'HeartDiseaseorAttack': 0, 'PhysActivity': 1, 'Fruits': 1, 'Veggies': 1, 'HvyAlcoholConsump': 0, 'AnyHealthcare': 1, 'NoDocbcCost': 0, 'GenHlth': 2, 'MentHlth': 0, 'PhysHlth': 0, 'DiffWalk': 0, 'Sex': 0, 'Age': 3, 'Education': 5, 'Income': 8}
patient_4 = Patient(name="Patient_4", data_dict=patient_4_data)

# Patient 5: Very High Risk - High BP, High Chol, Obese, Stroke history, Older
patient_5_data = {'HighBP': 1, 'HighChol': 1, 'CholCheck': 1, 'BMI': 40, 'Smoker': 1, 'Stroke': 1, 'HeartDiseaseorAttack': 1, 'PhysActivity': 0, 'Fruits': 0, 'Veggies': 0, 'HvyAlcoholConsump': 0, 'AnyHealthcare': 1, 'NoDocbcCost': 0, 'GenHlth': 5, 'MentHlth': 15, 'PhysHlth': 30, 'DiffWalk': 1, 'Sex': 1, 'Age': 13, 'Education': 3, 'Income': 2}
patient_5 = Patient(name="Patient_5", data_dict=patient_5_data)

# Patient 6: Good health - Low BMI, very active, young
patient_6_data = {'HighBP': 0, 'HighChol': 0, 'CholCheck': 1, 'BMI': 19, 'Smoker': 0, 'Stroke': 0, 'HeartDiseaseorAttack': 0, 'PhysActivity': 1, 'Fruits': 1, 'Veggies': 1, 'HvyAlcoholConsump': 0, 'AnyHealthcare': 1, 'NoDocbcCost': 0, 'GenHlth': 1, 'MentHlth': 0, 'PhysHlth': 0, 'DiffWalk': 0, 'Sex': 0, 'Age': 2, 'Education': 6, 'Income': 8}
patient_6 = Patient(name="Patient_6", data_dict=patient_6_data)

# Patient 7: High risk - High BP, High Chol, Heart Disease, older female
patient_7_data = {'HighBP': 1, 'HighChol': 1, 'CholCheck': 1, 'BMI': 35, 'Smoker': 0, 'Stroke': 0, 'HeartDiseaseorAttack': 1, 'PhysActivity': 0, 'Fruits': 0, 'Veggies': 0, 'HvyAlcoholConsump': 0, 'AnyHealthcare': 1, 'NoDocbcCost': 0, 'GenHlth': 4, 'MentHlth': 5, 'PhysHlth': 20, 'DiffWalk': 1, 'Sex': 0, 'Age': 10, 'Education': 4, 'Income': 4}
patient_7 = Patient(name="Patient_7", data_dict=patient_7_data)

# Patient 8: Moderate risk - High BP, Smoker, Heavy Alcohol Consumption
patient_8_data = {'HighBP': 1, 'HighChol': 1, 'CholCheck': 1, 'BMI': 30, 'Smoker': 1, 'Stroke': 0, 'HeartDiseaseorAttack': 0, 'PhysActivity': 0, 'Fruits': 0, 'Veggies': 1, 'HvyAlcoholConsump': 1, 'AnyHealthcare': 1, 'NoDocbcCost': 0, 'GenHlth': 3, 'MentHlth': 2, 'PhysHlth': 5, 'DiffWalk': 0, 'Sex': 1, 'Age': 12, 'Education': 5, 'Income': 6}
patient_8 = Patient(name="Patient_8", data_dict=patient_8_data)

# Patient 9: Low risk - Active, Good diet, average BMI
patient_9_data = {'HighBP': 0, 'HighChol': 0, 'CholCheck': 1, 'BMI': 25, 'Smoker': 0, 'Stroke': 0, 'HeartDiseaseorAttack': 0, 'PhysActivity': 1, 'Fruits': 1, 'Veggies': 1, 'HvyAlcoholConsump': 0, 'AnyHealthcare': 1, 'NoDocbcCost': 0, 'GenHlth': 2, 'MentHlth': 0, 'PhysHlth': 0, 'DiffWalk': 0, 'Sex': 0, 'Age': 5, 'Education': 6, 'Income': 8}
patient_9 = Patient(name="Patient_9", data_dict=patient_9_data)

# Patient 10: Moderate risk - Smoker, slightly older
patient_10_data = {'HighBP': 0, 'HighChol': 0, 'CholCheck': 1, 'BMI': 27, 'Smoker': 1, 'Stroke': 0, 'HeartDiseaseorAttack': 0, 'PhysActivity': 1, 'Fruits': 0, 'Veggies': 1, 'HvyAlcoholConsump': 0, 'AnyHealthcare': 1, 'NoDocbcCost': 0, 'GenHlth': 2, 'MentHlth': 0, 'PhysHlth': 0, 'DiffWalk': 0, 'Sex': 1, 'Age': 7, 'Education': 5, 'Income': 7}
patient_10 = Patient(name="Patient_10", data_dict=patient_10_data)

patient_instances = [
    patient_1, patient_2, patient_3, patient_4, patient_5,
    patient_6, patient_7, patient_8, patient_9, patient_10
]

for p in patient_instances:
    p.preprocess_and_predict(scaler, xgb_model)

results_list = []
for p in patient_instances:
    results_list.append({
        'Patient Object': p.name,
        'Probability': f"{p.probability:.2%}",
        'Final Prediction': p.prediction
    })

display(pd.DataFrame(results_list))

